import { QuizConfig, QuizQuestion } from '../types';

/**
 * Service to generate dynamic AI quizzes using Google Gemini API via backend proxy.
 *
 * @param config Quiz settings containing subject, difficulty, and number of questions.
 * @returns Promise resolving to an array of QuizQuestions generated by Gemini.
 */
export async function generateAiQuiz(config: QuizConfig): Promise<QuizQuestion[]> {
  const { subject, difficulty, numQuestions } = config;

  try {
    const res = await fetch('/api/quiz', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        subject,
        difficulty,
        numQuestions,
      }),
    });

    if (!res.ok) {
      throw new Error('Unable to generate AI quiz. Please try again.');
    }

    const data = await res.json();

    if (data && Array.isArray(data.questions) && data.questions.length > 0) {
      return data.questions as QuizQuestion[];
    }

    throw new Error('Unable to generate AI quiz. Please try again.');
  } catch (error: any) {
    console.error('aiQuizService error:', error?.message || error);
    throw new Error('Unable to generate AI quiz. Please try again.');
  }
}
